NumPy (Numerical Python) is an open source Python library that’s widely used in science and engineering. The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional ndarray, and a large library of functions that operate efficiently on these data structures.

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. 

Why NumPy?
Fast: Implemented in C, much faster than Python lists
Memory-efficient: Arrays consume less memory
Convenient: Vectorized operations, broadcasting, and indexing

In [ ]:
import numpy as np
# Creating a basic NumPy array
arr = np.array([1, 2, 3, 4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
# Creating NumPy Arrays
# 1D Array
arr = np.array([1,2,3])
# 2D Array
arr2d = np.array([[1,2,3],[4,5,6]])
# 3D Array
arr3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

# print("1D array:", arr)
# print("2D array:", arr2d)

print("3D array:", arr3d)

3D array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Special Arrays

In [ ]:
# 1. np.zeros(shape)
# Creates a NumPy array filled entirely with zeros.
# shape can be a single number (1D array) or a tuple (multi-dimensional array).
# Example:

import numpy as np

arr = np.zeros((2,3))  # 2 rows, 3 columns
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# 2. np.ones(shape)
# Creates an array filled with ones. Works like zeros but with 1 instead of 0.
# Example:

arr = np.ones((3,2))  # 3 rows, 2 columns
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# 3. np.full(shape, value)
# Creates an array filled with a specific value you choose.
# Example:

arr = np.full((2,2), 7)  # 2x2 array filled with 7
print(arr)

In [ ]:
# 4. np.eye(n)
# Creates an identity matrix of size n x n.
# Diagonal elements = 1
# Off-diagonal elements = 0
# Example:

arr = np.eye(3)  # 3x3 identity matrix
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 5. np.arange(start, stop, step)
# Creates a 1D array of numbers starting from start (inclusive) to stop (exclusive) with a given step.

# Example:

arr = np.arange(0, 10, 2)
print(arr)

[0 2 4 6 8]


In [ ]:
# 6. np.linspace(start, stop, num)
# Creates a 1D array of num evenly spaced numbers between start and stop (both inclusive).

# Example:

arr = np.linspace(0, 1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


how it works in 3D

In [ ]:
# 1. np.zeros() in 3D
# Just pass a 3-tuple for the shape (depth, rows, columns) → depth is like “number of matrices”, rows x columns are inside each matrix.

import numpy as np

arr = np.zeros((2,3,4))  # 2 matrices, each 3x4
print(arr)
print(arr.shape)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
(2, 3, 4)


In [11]:
# 2. np.ones() in 3D
arr = np.ones((3,2,2))  # 3 layers, 2x2 each
print(arr)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [13]:
# 3. np.full() in 3D
arr = np.full((2,2,3), 5)  # 2 layers, 2x3 each, filled with 7
print(arr)

[[[5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]]]


In [ ]:
# 4. np.eye() in 3D
# np.eye() is only for 2D square matrices, but you can stack them to make 3D arrays.

eye3d = np.array([np.eye(3) for _ in range(2)])  # 2 layers of 3x3 identity
print(eye3d)

[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]]


In [ ]:
# 5. np.arange() in 3D
# arange generates 1D arrays, but you can reshape it into 3D.

arr = np.arange(24).reshape(2,3,4)  # 2 layers, 3 rows, 4 columns
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
# 6. np.linspace() in 3D
# linspace generates 1D evenly spaced numbers → reshape to 3D if needed.

arr = np.linspace(0, 1, 24).reshape(2,3,4)
print(arr)

[[[0.         0.04347826 0.08695652 0.13043478]
  [0.17391304 0.2173913  0.26086957 0.30434783]
  [0.34782609 0.39130435 0.43478261 0.47826087]]

 [[0.52173913 0.56521739 0.60869565 0.65217391]
  [0.69565217 0.73913043 0.7826087  0.82608696]
  [0.86956522 0.91304348 0.95652174 1.        ]]]


 Array Attributes 
 These attributes help understand the shape, type, and structure of arrays. 


In [ ]:

# 1. arr.shape
# .shape tells you the dimensions of the array.
# It returns a tuple representing the size along each axis.
# For a 2D array: (rows, columns)
# For a 3D array: (layers, rows, columns)
# Example:

arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [7]:
# 2. arr.ndim
# .ndim tells you the number of dimensions (axes) of the array.
# 1D → 1, 2D → 2, 3D → 3, etc.
# Example:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr.ndim)

2


In [8]:
# 3. arr.size
# .size returns the total number of elements in the array.
# Formula: size = product of all dimensions
# Example:

print(arr.size)

6


In [9]:
# 4. arr.dtype
# .dtype shows the data type of the elements stored in the array.
# Common types:
# int32 or int64 → integers
# float32 or float64 → floating numbers
# bool → True/False
# Example:

print(arr.dtype)

int64


In [ ]:
# 5. arr.itemsize
# .itemsize returns the size in bytes of each element in the array.
# Important for memory management.
# Example:

print(arr.itemsize)

8


Indexing
Array indexing in NumPy refers to the method of accessing specific elements or subsets of data within an array.

In [10]:
import numpy as np

arr=np.array([1,2,3,4,5,6])
print(arr[2])


3


In [15]:
# 2D Arrays: We can access elements by specifying both row and column indices like matrix[row, column]

arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)
print(arr2[2,2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
9


In [19]:
# 3D Arrays: It can be visualized as a stack of 2D arrays, we need three indices-

# Depth: Specifies the 2D slice.
# Row: Specifies the row within the slice.
# Column: Specifies the column within the row.
arr3 = np.arange(24).reshape(2,3,4)  # 2 layers, 3 rows, 4 columns
print(arr3)
print(arr3[0,2,2])
print(arr3[1,1,1])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
10
17


Slicing Arrays
It allows us to extract a range of elements using the format start:stop:step.

In [20]:
# Slicing 1D Arrays: For a 1D array, slicing returns a subset of elements between the start and stop indices.


a1=np.array([10,20,30,40,50,60,70])
print(a1[3:6])


[40 50 60]


In [26]:
# Slicing Multidimensional 
# Arrays: In this slicing can be applied to each dimension separately which allows us to extract submatrices or smaller blocks of data.

a2=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a2)
print(a2[1:,1:])
print(a2[0:2,1:])
print(a2[0:2,0:2])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[50 60]
 [80 90]]
[[20 30]
 [50 60]]
[[10 20]
 [40 50]]


In [31]:
# 3D array
a3=np.arange(24).reshape(2,3,4)
print(a3)
print(a3[:,1:3,1:3])
print(a3[0,1:3,1:3])
print(a3[1,1:,0:2])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 5  6]
  [ 9 10]]

 [[17 18]
  [21 22]]]
[[ 5  6]
 [ 9 10]]
[[16 17]
 [20 21]]


Reshaping in NumPy refers to modifying the dimensions of an existing array without changing its data. The reshape() function is used for this purpose. It reorganizes the elements into a new shape, which is useful in machine learning, matrix operations and data preparation.

Reshaping changes how data is organized into rows, columns, or dimensions while keeping the same elements.

Total elements must remain the same

Formula:

rows × columns × layers = total elements

In [ ]:
# 1D to 2D reshaping
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
r = a.reshape(2, 3)
print(r)

In [ ]:
# 1D to 3D reshaping
arr = np.arange(1,13)
new_arr = arr.reshape(2,2,3)
print(new_arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# check the shape of the array
print(new_arr.shape)

(2, 2, 3)


Automatic Dimension (-1)
NumPy can automatically calculate one dimension.

In [6]:
arr = np.arange(12)
new_arr = arr.reshape(3, -1)
print(new_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


When Reshape Fails
If the number of elements does not match, NumPy gives an error.

In [7]:
arr = np.arange(10)

arr.reshape(3,3)

ValueError: cannot reshape array of size 10 into shape (3,3)

Questions

In [ ]:

# 1.arr = np.arange(1,13) convert in to 2D
arr = np.arange(1,13) 
arr1=arr.reshape(4,3)
print(arr1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
#2. arr = np.arange(24) convert into 3D
arr =np.arange(24)
arr2=arr.reshape(2,3,4)
print(arr2)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [17]:
#3.arr = np.arange(1,25)
# convter into 3D then find the result of this arr[:,1,:]
arr=np.arange(1,25)
arr3=arr.reshape(2,3,4)
print(arr3)
print("___________________")
print(arr3[:,1,:])




[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
___________________
[[ 5  6  7  8]
 [17 18 19 20]]


In [ ]:
# 4.arr = np.arange(27).reshape(3,3,3)
# Extract the middle layer.

arr = np.arange(27).reshape(3,3,3)
print(arr)
print("Extract the middle layers")
print(arr[:,1,:])
print("Extract the sepecifc elements")
print(arr[:,0:2,1:])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Extract the middle layers
[[ 3  4  5]
 [12 13 14]
 [21 22 23]]
Extract the sepecifc elements
[[[ 1  2]
  [ 4  5]]

 [[10 11]
  [13 14]]

 [[19 20]
  [22 23]]]
[[ 0  1]
 [ 9 10]]


In [26]:
arr = np.arange(12)
arr = arr.reshape(3,4)
print(arr)
print(arr[:,1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[1 5 9]


The numpy.resize() function is used to change the size of an existing NumPy array. It modifies the array permanently and adjusts its shape to the new dimensions. If the new shape requires more elements than available, NumPy repeats the array elements. If less space is required, elements are truncated.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
# arr.resize((2, 3))
# resize add the element 
# arr.resize((3,4))   
# resize remove the element
arr.resize((2, 2))
print(arr)

[[1 2]
 [3 4]]


Transpose means flipping the array over its diagonal.

In [32]:
arr=np.arange(1,13)
arr=arr.reshape(4,3)
print(arr)
print("transpose array:\n",arr.T)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
transpose array:
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


Splitting arrays means dividing a single NumPy array into multiple smaller sub-arrays. NumPy provides several functions that make this easy by allowing you to split arrays along different directions (rows, columns, depth).


In [37]:
# np.split() divides an array into equal parts.

# Syntax
# np.split(array, number_of_splits)
arr = np.array([10,20,30,40,50,60])
result = np.split(arr,3)
# result = np.split(arr,5)

print(result)

[array([10, 20]), array([30, 40]), array([50, 60])]


In [35]:
# np.array_split()
# Unlike split(), this function can divide arrays unevenly.
arr=np.arange(1,13)
res=np.array_split(arr,5)
print(res)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8]), array([ 9, 10]), array([11, 12])]


In [57]:
# np.hsplit() (Horizontal Split)
# Splits arrays column-wise.
arr=np.arange(1,13)
arr=arr.reshape(3,4)
print(arr)
res=np.hsplit(arr,2)
print(res)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


In [ ]:
# numpy.vsplit() performs vertical splitting, meaning it divides a matrix row-wise (along axis=0). 
# It works only on arrays with 2 or more dimensions
arr=np.arange(1,25)
arr=arr.reshape(2,4,3)
print(arr)
res=np.vsplit(arr,2)
print(res)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]
[array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]]), array([[[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])]
(2, 4, 3)


In [ ]:
# numpy.dsplit() is used for 3D arrays. It splits the array along the third axis (axis=2). 
# This is useful when working with stacked matrices, images, or multi-channel data.
arr = np.arange(24).reshape((2, 3, 4))
res = np.dsplit(arr, 2)
print(res)

[array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]]), array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])]


In [1]:
import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr[::2, 1:])

[[2]
 [6]]
